### ISSUE TITLE
Definition of feq

### ISSUE THREAD

**Issue by jpfr** [anse1/stubforth#1]
Hey there,

```
fbinop(feq, f=, =)
```
should be
```
fbinop(feq, f=, ==)
```

A sane compiler should generate a warning for the original generated code `fp[-2] = fp[-2] = fp[-1];`.
But most compilers need flags (Wall, Wextra on gcc).

**Comment by anse1** [comment]
Thanks for the report!

Sidenote: There actually is a big fat warning when building the master branch, but I guess since I almost exclusively build stubforth on embedded things that don't include the floating word set, I missed it for years.
